### Get all books
GET http://localhost:8080/api/books

### Get single book
GET http://localhost:8080/api/books/16699753-4300-4482-9959-2e5ab53788c2

### Get single book not existing
GET http://localhost:8080/api/books/16699753-4300-4482-9959-2e5ab53788c3

### Get all authors
GET http://localhost:8080/api/authors

### Get single author
GET http://localhost:8080/api/authors/b26c7fb7-0422-45e4-8e8e-03dbc772f98c

### Get single author not existing
GET http://localhost:8080/api/authors/b26c7fb7-0422-45e4-8e8e-03dbc772f98a

### Get author books
GET http://localhost:8080/api/authors/b26c7fb7-0422-45e4-8e8e-03dbc772f98c/books

### Get author books not existing
GET http://localhost:8080/api/authors/b26c7fb7-0422-45e4-8e8e-03dbc772f98a/books

### Create new book
PUT http://localhost:8080/api/books/b26c7fb7-0422-45e4-8e8e-03dbc772f98b
Content-Type: application/json

{
  "title": "Nowa ksiazka",
  "pages": 2222,
  "author": "b26c7fb7-0422-45e4-8e8e-03dbc772f98c"
}

### Create new book not existing author
PUT http://localhost:8080/api/books/b26c7fb7-0422-45e4-8e8e-03dbc772f98b
Content-Type: application/json

{
  "title": "Nowa ksiazka",
  "pages": 2222,
  "author": "b26c7fb7-0422-45e4-8e8e-03dbc772f98a"
}

### Create new author
PUT http://localhost:8080/api/authors/b26c7fb7-0422-45e4-8e8e-28dbc772f98c
Content-Type: application/json

{
  "name": "Nowy autor",
  "age": 19
}

### Get author books empty
GET http://localhost:8080/api/authors/b26c7fb7-0422-45e4-8e8e-28dbc772f98c/books

### Delete book
DELETE http://localhost:8080/api/books/16699753-4300-4482-9959-2e5ab53788c2

### Delete book not existing
DELETE http://localhost:8080/api/books/16699753-4300-4482-9959-2e5ab53788c2

### Delete author
DELETE http://localhost:8080/api/authors/3c4148e3-d1d7-4841-8b57-96d4b69d78e8

### Delete author not existing
DELETE http://localhost:8080/api/authors/3c4148e3-d1d7-4841-8b57-96d4b69d78e8
